#pragma once

#define CLIP_VER_MAJOR 1
#define CLIP_VER_MINOR 4
#define CLIP_VER_PATCH 0
#define CLIP_VER_BUILD 0

#define CLIP_VER_NUMERIC CLIP_VER_MAJOR,CLIP_VER_MINOR,CLIP_VER_PATCH,CLIP_VER_BUILD
#define CLIP_VER_STRING "1.4.0.0"